"""LLM instructions and the three tools. Talks to the inbox and to Memory.

A tool never starts work itself. It posts one event and returns, so the
Conductor stays the only thing that decides what happens next.
"""

from __future__ import annotations

import asyncio
import re
from dataclasses import dataclass
from typing import Any

from livekit.agents import Agent, RunContext, function_tool
from livekit.agents.llm import StopResponse

from events import ResearchRequested, ResearchStopRequested
from memory import LevelResult, Memory

GREETING = "こんにちは。社内Wikiを検索できます。音声またはテキストで質問してください。"

# Spoken verbatim by Speaker.start_notice, never regenerated by the LLM.
NOTICE_STOPPED = "調査を止めました。"
NOTICE_NOTHING_TO_REPEAT = "繰り返せる回答はまだありません。"
NOTICE_NOTHING_TO_CONTINUE = "途中の回答はありません。"
NOTICE_CLOSED = "わかりました。"
NOTICE_ACKNOWLEDGED = "はい、どうぞ。"
NOTICE_RESEARCH_FAILED = "調査との接続が切れました。届いている内容はそのまま確認できます。"

_SHARED_VOICE_RULES = (
    "出力は日本語だけにしてください。英字、英単語、ローマ字、ASCIIの記号、Markdown、"
    "箇条書き記号、コードフェンス、URL、パス、表、引用記法は一切出力しません。"
    "ファイル名、定義名、API名、関数名、マクロ名など、質問への直接回答となる重要な固有名詞は"
    "説明だけに置き換えず、構成要素と拡張子を省略しないカタカナ読みで必ず言ってください。"
    "英数字の名称は構成要素を落とさずカタカナの自然な読みに変換し、"
    "アンダースコア、ハイフン、ピリオド自体は読みません。"
    "意味が明確な略語は自然な語にします。たとえば mpf_mfs_open は"
    "『エムピーエフ・エムエフエス・オープン』、mpf_buf は『エムピーエフ・バッファ』、"
    "pmf_prg.txt は『ピーエムエフ・プログラム・テキスト・ファイル』のように扱います。"
    "ファイルの拡張子も省略せず、txt は『テキスト・ファイル』のように読みます。"
)

ASSISTANT_INSTRUCTIONS = (
    "あなたは日本語で話す社内Wikiアシスタントです。"
    + _SHARED_VOICE_RULES
    + "音声では短く自然な敬語を使います。"
    "挨拶、雑談、一般的な質問には自然に会話として答えてください。"
    "社内Wikiの確認、社内固有の事実、最新情報の調査が必要な質問だけ research_wiki を使ってください。"
    "関数、マクロ、API、構造体、引数、戻り値、エラーコードの質問は、推測や一般的な例で答えず、"
    "必ず最初に research_wiki を使ってください。"
    "ただし、すでに調べた内容についての詳細、理由、具体例、別の引数、制約、言い換え、"
    "『もっと詳しく』のような追質問は新規調査ではありません。"
    "その場合は read_result で保持済みの根拠を読み、そこにある情報だけで詳しく説明してください。"
    "read_result を使った追質問では、『確認します』『調べます』のような前置きだけで終わらせず、"
    "同じ応答で結論から答えてください。"
    "ユーザーが調査の中止を求めたときは stop_research を使ってください。"
    "research_wiki を呼んだ直後は、調査開始、計画、途中経過、画面の案内、推測した回答を音声で言わず、"
    "その応答を終了してください。調査結果は別の指示が音声にします。"
)


@dataclass
class AssistantDeps:
    """Everything the tools are allowed to touch."""

    inbox: asyncio.Queue
    memory: Memory


@function_tool
async def research_wiki(ctx: RunContext[AssistantDeps], question: str) -> str:
    """Search the internal Wiki for a question that needs company-specific facts."""
    ctx.userdata.inbox.put_nowait(ResearchRequested(question))
    # Tool-level stop is deliberate: a prompt alone cannot reliably stop a model
    # from voicing a speculative "I'll look that up" before the answer exists.
    raise StopResponse()


@function_tool
async def read_result(ctx: RunContext[AssistantDeps], handle: str) -> str:
    """Read a retained Wiki result before answering a related follow-up question."""
    level: LevelResult | None = ctx.userdata.memory.find(handle)
    if level is None:
        return "保持している調査結果はまだありません。"
    return f"[観点] {level.objective}\n[質問] {level.question}\n[内容]\n{level.text}"


@function_tool
async def stop_research(ctx: RunContext[AssistantDeps]) -> str:
    """Stop every running Wiki investigation."""
    ctx.userdata.inbox.put_nowait(ResearchStopRequested())
    raise StopResponse()


class Assistant(Agent):
    def __init__(self) -> None:
        super().__init__(
            instructions=ASSISTANT_INSTRUCTIONS,
            tools=[research_wiki, read_result, stop_research],
        )

    async def on_user_turn_completed(self, turn_ctx: Any, new_message: Any) -> None:
        # The pipeline's own reply is always suppressed. Attention decides
        # whether this was a turn, and the Conductor asks for the reply.
        raise StopResponse()


# ---------------------------------------------------------------------------
# Report prompts - the LLM pass that turns internal evidence into speech
# ---------------------------------------------------------------------------


def _objective_phrase(objective: str) -> str:
    value = re.sub(
        r"(?:を|について)?(?:特定|確認|検証|説明|調査|整理|比較|把握|評価)する$",
        "",
        (objective or "").strip(),
    )
    return value[:34] or "必要な情報"


def plan_preview_instructions(question: str, planned_levels: list[dict[str, Any]]) -> str:
    outline = "\n".join(
        f"{index + 1}. {level.get('objective') or '必要な情報'}"
        for index, level in enumerate(
            sorted(planned_levels, key=lambda level: int(level.get("position") or 0))
        )
    )
    return (
        "以下は社内Wiki調査の内部的な段階計画です。ユーザーに、これから何を確認し、"
        "どの順で説明するかを自然な日本語一文で予告してください。"
        "検索語、件数、段階番号、箇条書き、計画という言葉、Markdown、英字、ローマ字、"
        "アンダースコア、ハイフンは出力しません。内部の観点をそのまま列挙せず、"
        "例えば『まず関数の役割を確認し、そのあと引数の意味を見ます』のように"
        "会話として言い換えてください。まだ事実の回答や推測はしないでください。"
        "追加の調査やツール呼び出しはしないでください。\n\n"
        f"[ユーザーの質問]\n{question}\n\n"
        f"[内部の段階計画]\n{outline}"
    )


def report_instructions(
    level: LevelResult,
    *,
    step: int,
    step_count: int,
    next_objective: str = "",
    resume: bool = False,
    attribute: bool = False,
) -> str:
    """One level of evidence, spoken as two to four sentences."""
    lead = ""
    if attribute:
        lead = (
            f"この内容は今の話題ではなく、先ほどの『{_objective_phrase(level.question)}』"
            "という質問への回答です。必ず『さっきの件ですが、』のように、"
            "前の質問の答えだと分かる一言から始めてください。"
        )
    if resume and level.spoken_text:
        lead += (
            "この説明は途中で中断されました。すでに話した部分を繰り返さず、"
            "『続きですが、』のように自然につないで、その先だけを話してください。\n"
            f"[すでに話した部分]\n{level.spoken_text[-400:]}\n"
        )

    return (
        "以下は社内Wiki調査の一段階の内部結果です。ユーザーには、この段階で確定した"
        "質問への答えだけを、自然な日本語で二から四文、二百四十文字程度までで話してください。"
        + lead
        + "最初にユーザーの質問で直接求められた結論を述べ、その名前だけで終わらせず、"
        "その値・引数・用語が何を指定するのかを平易な日本語で一段深く説明してください。"
        "根拠に範囲、単位、入出力の向き、条件、構成要素がある場合は、質問に役立つものだけを補足してください。"
        "根拠に単純な足し算や引き算で得られる値がある場合は、計算過程を短く示して結論の数値まで言ってください。"
        "関連する別関数、周辺機能、実装例、カテゴリ一覧、背景説明、検索で見つけた周辺情報は、"
        "質問への直接回答に不可欠でない限り絶対に話しません。"
        "これは内部状態なので、内容を列挙・引用・復唱したり、画面を見るよう案内したり、"
        "調査の計画・進捗・エラー・検索語を話したりしないでください。"
        + _SHARED_VOICE_RULES
        + "名称を示した後は、技術的な生データの羅列を避け、何をするものかを説明してください。"
        "これは単独の回答ではなく、段階的な説明の途中です。前の段階の内容を繰り返さず、"
        "この段階で新たに分かったことだけを話してください。"
        "次の観点が示されている場合は、内容を言い終えた後に一度だけ自然に"
        "『続けて、引数の意味を確認します』のように次の話題へつないでください。"
        "最後の段階では次の調査を予告せず、質問への答えを短く締めてください。"
        "未確定の内容は断定せず、追加の調査やツール呼び出しはしないでください。\n\n"
        f"[ユーザーの質問]\n{level.question}\n\n"
        f"[説明の段階]\n{step} / {step_count}\n\n"
        f"[この段階の観点]\n{level.objective}\n\n"
        f"[次の観点]\n{next_objective or 'なし。ここで説明を締める。'}\n\n"
        f"[内部結果]\n{level.text[:5000]}"
    )
