[project]
name = "llm-wiki-realtime"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "livekit>=1.1.14",
    "livekit-agents>=1.6.8",
    "livekit-api>=1.2.0",
    "livekit-plugins-openai>=1.6.8",
    "livekit-plugins-silero>=1.6.8",
    "livekit-plugins-turn-detector>=1.6.8",
    "python-dotenv>=1.2.2",
    "trustme>=1.2.1",
    "uvicorn>=0.52.1",
]
