"""Every string the user can hear.

The greeting, the fixed notices, the assistant's standing instructions and the
two prompt builders that turn internal evidence into speech all live here, so
that changing what the assistant says never means opening a wiring file.
"""

from __future__ import annotations

import random
import re
from typing import Any

from app.core.memory import LevelResult

GREETING = "もしもし！ＡＩみなとです。チャットで何でも質問するか、オーブをクリックして話しかけてください。"

# Spoken verbatim by Speaker.start_notice, never regenerated by the LLM.
# Fills the 5-7s gap between research_wiki starting and the plan preview
# actually arriving (stream connect + plan frame + its own LLM pass) with
# something immediate: a fixed sentence needs no LLM round trip at all.
NOTICE_RESEARCHING_VARIANTS = (
    "社内ウィキを確認しています。すぐにお伝えします。",
    "関連する情報を社内ウィキで確認しています。",
    "必要な情報を確認中です。まとまり次第お伝えします。",
    "社内ウィキから関連する内容を探しています。",
    "ただいま社内ウィキを確認しています。",
    "関連する資料を確認しています。すぐに続けます。",
    "社内ウィキで必要な内容を調べています。",
    "回答に必要な情報を確認しています。",
    "社内の資料を確認しています。もう少しでお伝えします。",
    "関連する情報をまとめています。すぐにお伝えします。",
)


def researching_notice() -> str:
    """Return one of the short research notices for this run."""
    return random.choice(NOTICE_RESEARCHING_VARIANTS)
NOTICE_STOPPED = "調査を止めました。"
NOTICE_NOTHING_TO_REPEAT = "繰り返せる回答はまだありません。"
NOTICE_NOTHING_TO_CONTINUE = "途中の回答はありません。"
NOTICE_CLOSED = "わかりました。"
NOTICE_ACKNOWLEDGED = "はい、どうぞ。"
NOTICE_RESEARCH_FAILED = "調査との接続が切れました。届いている内容はそのまま確認できます。"

_SHARED_VOICE_RULES = (
    "出力は日本語だけにしてください。英字、英単語、ローマ字、ASCIIの記号、Markdown、"
    "箇条書き記号、コードフェンス、URL、パス、表、引用記法は一切出力しません。"
    "ファイル名、定義名、API名、関数名、マクロ名など、質問への直接回答となる重要な固有名詞は"
    "説明だけに置き換えず、構成要素と拡張子を省略しないカタカナ読みで必ず言ってください。"
    "英数字の名称は構成要素を落とさずカタカナの自然な読みに変換し、"
    "アンダースコア、ハイフン、ピリオド自体は読みません。"
    "意味が明確な略語は自然な語にします。たとえば mpf_mfs_open は"
    "『エムピーエフ・エムエフエス・オープン』、mpf_buf は『エムピーエフ・バッファ』、"
    "pmf_prg.txt は『ピーエムエフ・プログラム・テキスト・ファイル』のように扱います。"
    "ファイルの拡張子も省略せず、txt は『テキスト・ファイル』のように読みます。"
)

ASSISTANT_INSTRUCTIONS = (
    "あなたの名前はＡＩみなとです。ＡＩ Ｍｉｎａｔｏとも表記されます。"
    "名前を聞かれたときや自己紹介するときは、必ずＡＩみなとと名乗ってください。"
    "あなたは日本語で話す社内ウィキアシスタントです。"
    + _SHARED_VOICE_RULES
    + "音声では短く自然な敬語を使います。"
    # The router. Two branches, casual is a closed list, and everything that is
    # not on that list researches. Anything vaguer than this gets read as "only
    # company-internal trivia needs the wiki", and public technical topics --
    # which the wiki is largely made of -- get answered from the model's own
    # knowledge instead of from the book.
    "ユーザーの発話は二種類しかありません。どちらか迷ったら必ず調査を選んでください。"
    "一つ目は雑談です。挨拶、相槌、お礼、聞き返し、自己紹介や使い方の確認、"
    "天気や体調のような世間話だけが雑談です。"
    "雑談にはツールを使わず、一文か二文で即座に答えてください。"
    "二つ目はそれ以外のすべての質問です。技術的な内容、事実の確認、手順、仕様、"
    "設定、用語の意味は、すべてこちらに入ります。必ず最初に research_wiki を使ってください。"
    "答えを知っていると思っても、一般に公開された技術の話題でも、社内ウィキには"
    "一般的な技術文書も含まれているため、自分の知識や記憶から答えてはいけません。"
    "関数、マクロ、API、構造体、引数、戻り値、エラーコード、設定値、コマンド、"
    "ファイル形式、オプションや定数の一覧に関する質問は、例外なく research_wiki を使い、"
    "推測や一般的な例では答えません。"
    "唯一の例外は、直前に調査した対象そのものについての追質問です。"
    "すでに調べた内容の詳細、理由、具体例、制約、言い換え、"
    "『もっと詳しく』のような追質問は新規調査ではありません。"
    "その場合は read_result で保持済みの根拠を読み、そこにある情報だけで詳しく説明してください。"
    "ただし read_result の内容に、今回質問された値、条件、手順、理由、詳細が明示されていない場合は、"
    "同じ話題の追質問でも保持済みの結果では答えられません。直ちに research_wiki を呼び出してください。"
    "そのとき、保持済みの情報、以前の回答、記載の有無、不足、確認できないことには一切触れません。"
    "『保持している情報にない』『前の結果にはない』『改めて詳細を調べます』のような返答は絶対にしません。"
    "research_wiki を呼んだ後は、追加の文章を出力せず応答を終了してください。"
    "ただし、前の回答で扱っていない名前、たとえば別の関数名、API名、マクロ名、構造体名、"
    "ファイル名などが質問に出てきた場合は追質問ではありません。"
    "話題が続いていても、新しい調査として research_wiki を使ってください。"
    "read_result が該当する結果はないと答えた場合も、記憶から答えず、"
    "その場で research_wiki を使ってください。"
    # The one case where not researching is correct: the answer is already on
    # its way. Without this the model re-opens a run for a level the live plan
    # is fetching right now, and the user hears the same question researched twice.
    "ただし read_result が、その観点は今調べているところだと答えた場合は、"
    "同じ内容を research_wiki で調べ直さないでください。"
    "その場合は『今調べていますので、少しお待ちください』のように一言だけ伝えて応答を終えます。"
    "届いた結果は別の指示が音声にします。"
    "文脈に『調査中でまだ届いていない観点』が示されている場合、"
    "そこに含まれる内容についても新しい調査を始めず、同じように待つと伝えてください。"
    "read_result を使った追質問では、『確認します』『調べます』のような前置きだけで終わらせず、"
    "同じ応答で結論から答えてください。"
    "ユーザーが調査の中止を求めたときは stop_research を使ってください。"
    "research_wiki を呼んだ直後は、調査開始、計画、途中経過、画面の案内、推測した回答を音声で言わず、"
    "その応答を終了してください。調査結果は別の指示が音声にします。"
)


# ---------------------------------------------------------------------------
# Report prompts - the LLM pass that turns internal evidence into speech
# ---------------------------------------------------------------------------


def _objective_phrase(objective: str) -> str:
    value = re.sub(
        r"(?:を|について)?(?:特定|確認|検証|説明|調査|整理|比較|把握|評価)する$",
        "",
        (objective or "").strip(),
    )
    return value[:34] or "必要な情報"


def plan_preview_instructions(question: str, planned_levels: list[dict[str, Any]]) -> str:
    outline = "\n".join(
        f"{index + 1}. {level.get('objective') or '必要な情報'}"
        for index, level in enumerate(
            sorted(planned_levels, key=lambda level: int(level.get("position") or 0))
        )
    )
    # A plan of one stage is the backend saying it expects to be done in one
    # answer. Told to preview "what comes first and what comes next", the model
    # invents a second step to fill the slot -- 「定義を探して、そのあと引数の
    # 意味を確認します」 for a run that then answers and stops. Only a plan that
    # really has a next stage may promise one.
    if len(planned_levels) <= 1:
        shape = (
            "これから何を調べるのかだけを、自然な日本語一文で短く伝えてください。"
            "手順を分けて説明しないでください。"
            "『まず』『そのあと』『続いて』『次に』のように、"
            "このあとに別の段階が続くと受け取れる言い方は使わないでください。"
            "調査がこれで終わりだと明言する必要もありません。"
        )
    else:
        shape = (
            "ユーザーに、これから何を確認し、どの順で説明するかを自然な日本語一文で"
            "予告してください。内部の観点をそのまま列挙せず、"
            "例えば『まず関数の役割を確認し、そのあと引数の意味を見ます』のように"
            "会話として言い換えてください。"
            # This sentence is spoken once and never corrected, while the plan
            # below it is provisional: the backend appends stages mid-run. A
            # preview that closes the list is what makes a later third stage
            # sound like a detour instead of the rest of the answer.
            "この段階計画は調査の途中で増えたり分かれたりします。"
            "段階の数を言ったり、『この二点だけ』『以上の流れで説明します』のように"
            "これで全部だと受け取れる言い方をしたりしないでください。"
            "計画を最後まで言い切る必要はなく、"
            "まず何から確認し、次に何を見るかまで伝えれば十分です。"
        )
    return (
        "以下は社内ウィキ調査の内部的な段階計画です。"
        + shape
        + "検索語、件数、段階番号、箇条書き、計画という言葉、Markdown、英字、ローマ字、"
        "アンダースコア、ハイフンは出力しません。"
        "まだ事実の回答や推測はしないでください。"
        "追加の調査やツール呼び出しはしないでください。\n\n"
        f"[ユーザーの質問]\n{question}\n\n"
        f"[内部の段階計画]\n{outline}"
    )


def _bridge_rules(*, step: int, step_count: int, next_objective: str, last_closing_line: str) -> str:
    """The one sentence that hands off to the next stage.

    It is derived from the next objective alone, which is why a mid-run plan
    split breaks it: the stage that got split promised the whole of what it was
    about to say, then the half that survived the split promised it again, word
    for word, and the user hears two steps of no progress. Two signals fix that
    without a second speech turn - whether anything follows the next objective
    (so the hand-off stops sounding like the end), and what the previous
    hand-off actually said (so this one has to differ, or stand down).
    """
    if not next_objective:
        return "最後の段階では次の調査を予告せず、質問への答えを短く締めてください。"
    rules = (
        "内容を言い終えた後に、一度だけ自然に"
        "『続けて、引数の意味を確認します』のように次の話題へつないでください。"
    )
    if step + 1 < step_count:
        rules += (
            "次の観点のあとにも段階が残っています。そこで説明が終わるような締め方はせず、"
            "まだ続きがあると分かる言い方にしてください。"
        )
    if last_closing_line:
        rules += (
            "ただし直前の段階は『直前の締めの一文』で締めています。"
            "同じ文や、言い換えただけのほぼ同じ一文で締めてはいけません。"
            "次の観点が直前に予告した内容と実質同じで、違う締め方ができない場合は、"
            "次の話題へつなぐ一文自体を省き、この段階の答えだけで締めてください。"
        )
    return rules


def report_instructions(
    level: LevelResult,
    *,
    step: int,
    step_count: int,
    next_objective: str = "",
    resume: bool = False,
    attribute: bool = False,
    spoken_so_far: str = "",
    may_skip: bool = False,
    last_closing_line: str = "",
) -> str:
    """One level of evidence, spoken as two to four sentences - or as nothing.

    ``may_skip`` lets this same pass decide the level is not worth saying. The
    decision has to live here because an empty generation is the only way to
    reach that verdict without any of it having been voiced first.

    ``last_closing_line`` is how the hand-off at the end stays honest across a
    plan that changed under it; see ``_bridge_rules``.
    """
    lead = ""
    if attribute:
        lead = (
            f"この内容は今の話題ではなく、先ほどの『{_objective_phrase(level.question)}』"
            "という質問への回答です。必ず『さっきの件ですが、』のように、"
            "前の質問の答えだと分かる一言から始めてください。"
        )
    if resume and level.spoken_text:
        lead += (
            "この説明は途中で中断されました。すでに話した部分を繰り返さず、"
            "『続きですが、』のように自然につないで、その先だけを話してください。\n"
            f"[すでに話した部分]\n{level.spoken_text[-400:]}\n"
        )

    skip = ""
    if may_skip:
        # The RAG backend deliberately returns more than the question needs, so
        # that follow-ups can be answered from what it retained. Arriving and
        # being worth saying are different things, and this is where they split.
        skip = (
            "この段階の内部結果が、ユーザーの質問への答えとして新しく重要な事実を含まない場合、"
            "すでに話した内容の言い換えにすぎない場合、または質問に直接関係しない周辺情報だけの場合は、"
            "何も話さないでください。そのときは一文字も出力せず、空のまま応答を終えます。"
            "『特にありません』『追加の情報はありません』のような断りも言いません。"
            "逆に、質問への答えを具体的に前進させる新しい事実があるときは、短くても必ず話してください。"
        )

    return (
        "以下は社内ウィキ調査の一段階の内部結果です。ユーザーには、この段階で確定した"
        "質問への答えだけを、自然な日本語で二から四文、二百四十文字程度までで話してください。"
        + lead
        + skip
        + "最初にユーザーの質問で直接求められた結論を述べ、その名前だけで終わらせず、"
        "その値・引数・用語が何を指定するのかを平易な日本語で一段深く説明してください。"
        "根拠に範囲、単位、入出力の向き、条件、構成要素がある場合は、質問に役立つものだけを補足してください。"
        "根拠に単純な足し算や引き算で得られる値がある場合は、計算過程を短く示して結論の数値まで言ってください。"
        "関連する別関数、周辺機能、実装例、カテゴリ一覧、背景説明、検索で見つけた周辺情報は、"
        "質問への直接回答に不可欠でない限り絶対に話しません。"
        "これは内部状態なので、内容を列挙・引用・復唱したり、画面を見るよう案内したり、"
        "調査の計画・進捗・エラー・検索語を話したりしないでください。"
        + _SHARED_VOICE_RULES
        + "名称を示した後は、技術的な生データの羅列を避け、何をするものかを説明してください。"
        "これは単独の回答ではなく、段階的な説明の途中です。前の段階の内容を繰り返さず、"
        "この段階で新たに分かったことだけを話してください。"
        + _bridge_rules(
            step=step,
            step_count=step_count,
            next_objective=next_objective,
            last_closing_line=last_closing_line,
        )
        + "未確定の内容は断定せず、追加の調査やツール呼び出しはしないでください。\n\n"
        f"[ユーザーの質問]\n{level.question}\n\n"
        f"[説明の段階]\n{step} / {step_count}\n\n"
        f"[この段階の観点]\n{level.objective}\n\n"
        f"[次の観点]\n{next_objective or 'なし。ここで説明を締める。'}\n\n"
        + (f"[直前の締めの一文]\n{last_closing_line}\n\n" if next_objective and last_closing_line else "")
        + (f"[この質問についてすでに話した内容]\n{spoken_so_far}\n\n" if spoken_so_far else "")
        + f"[内部結果]\n{level.text[:5000]}"
    )
